name: Test Branch Name Action
on: [push, pull_request]

jobs:
    check-branch-name:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: 'Check branch name'
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          patterns: "feature/,fix/,chore/"